# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BASTIONfit_cpp <- function(edges, weights, Y, MCMC_iter, BURNIN, THIN, init_values, hyperpars) {
    .Call(`_BASTION_BASTIONfit_cpp`, edges, weights, Y, MCMC_iter, BURNIN, THIN, init_values, hyperpars)
}

